"""postgres

Revision ID: c22a0a88b4fa
Revises: a2cbf939122d
Create Date: 2022-08-31 18:37:29.242137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c22a0a88b4fa"
down_revision = "a2cbf939122d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
